import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider, ThemeProvider } from "./provider";
import { GoogleOAuthProvider } from '@react-oauth/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  );
}
